#!/bin/bash
# Set up a new development environment
# This script guides you through creating and configuring a dev Supabase project

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "=========================================="
echo "PolicyPocket Development Environment Setup"
echo "=========================================="
echo ""

# Check if supabase CLI is installed
if ! command -v supabase &> /dev/null; then
  echo "ERROR: Supabase CLI is not installed."
  echo "Install it with: brew install supabase/tap/supabase"
  exit 1
fi

echo "This script will help you set up a development environment."
echo ""
echo "Prerequisites:"
echo "  1. A Supabase account (https://supabase.com)"
echo "  2. A new Supabase project created for development"
echo ""
read -p "Have you created a new Supabase project for development? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo ""
  echo "Please create a new Supabase project first:"
  echo "  1. Go to https://supabase.com/dashboard"
  echo "  2. Click 'New Project'"
  echo "  3. Name it 'PolicyPocket Dev' (or similar)"
  echo "  4. Choose the free tier"
  echo "  5. Wait for the project to be created"
  echo ""
  echo "Then run this script again."
  exit 0
fi

echo ""
read -p "Enter your dev Supabase project ID (from Settings > General): " PROJECT_ID
read -p "Enter your dev Supabase anon key (from Settings > API): " ANON_KEY

# Validate inputs
if [ -z "$PROJECT_ID" ] || [ -z "$ANON_KEY" ]; then
  echo "ERROR: Project ID and anon key are required."
  exit 1
fi

# Create .env.development
cat > "$PROJECT_DIR/.env.development" << EOF
# Development Environment - PolicyPocket
# Auto-generated by setup-dev-env.sh

VITE_SUPABASE_URL="https://${PROJECT_ID}.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY="${ANON_KEY}"
VITE_SUPABASE_PROJECT_ID="${PROJECT_ID}"
VITE_APP_ENV="development"
EOF

echo ""
echo "Created .env.development with your credentials."

# Link Supabase project
echo ""
echo "Linking Supabase CLI to your dev project..."
cd "$PROJECT_DIR"
supabase link --project-ref "$PROJECT_ID"

# Push migrations
echo ""
read -p "Do you want to apply database migrations now? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Applying migrations..."
  supabase db push
  echo "Migrations applied successfully!"
fi

# Deploy Edge Functions
echo ""
read -p "Do you want to deploy Edge Functions to dev? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Deploying Edge Functions..."
  supabase functions deploy coverage-assistant
  supabase functions deploy extract-benefits
  echo "Edge Functions deployed!"

  echo ""
  echo "IMPORTANT: Set your ANTHROPIC_API_KEY in Supabase Dashboard:"
  echo "  1. Go to https://supabase.com/dashboard/project/${PROJECT_ID}/settings/vault"
  echo "  2. Add secret: ANTHROPIC_API_KEY = your-api-key"
fi

echo ""
echo "=========================================="
echo "Development environment setup complete!"
echo "=========================================="
echo ""
echo "To start developing:"
echo "  npm run dev"
echo ""
echo "To switch environments:"
echo "  ./scripts/switch-env.sh dev   # Development"
echo "  ./scripts/switch-env.sh prod  # Production"
echo ""
